name: Build & Deploy

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions/upload-artifact@v2
        with:
          name: website
          path: ./index.html

      - name: Deploy App to CapRover
        uses: caprover/deploy-from-github@v1.0.1
        with:
          server: ${{ secrets.CAPROVER_SERVER_NAME }}
          app: ${{ secrets.CAPROVER_APP_NAME }}
          token: ${{ secrets.CAPROVER_PASSWORD }}
